name: Update JSON

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run update script
      run: node update-json.js

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "No changes detected"
          echo "::set-output name=changes_detected::false"
        else
          echo "Changes detected"
          echo "::set-output name=changes_detected::true"
        fi

    - name: Commit and push changes if any
      if: steps.changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/nextFiveDays.json
        git commit -m "Update JSON file"
        git push origin main